// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// pwm //
// --- //

#define pwm_wrap_target 0
#define pwm_wrap 7

static const uint16_t pwm_program_instructions[] = {
            //     .wrap_target
    0xb042, //  0: nop                    side 0     
    0x80e0, //  1: pull   ifempty block              
    0x7028, //  2: out    x, 8            side 0     
    0xa046, //  3: mov    y, isr                     
    0x00a6, //  4: jmp    x != y, 6                  
    0x1807, //  5: jmp    7               side 1     
    0xa042, //  6: nop                               
    0x0184, //  7: jmp    y--, 4                 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pwm_program = {
    .instructions = pwm_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config pwm_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pwm_wrap_target, offset + pwm_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

